# Use an official Node.js runtime as a parent image
FROM node:20-alpine AS builder

# Set working directory
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the app's source code
COPY . .

# Build the NestJS app
RUN npm run build:apigateway


# Start the application
CMD ["node", "dist/apps/apigateway/main.js"]

# Expose app port
EXPOSE 8080
